# Generated by Django 3.0.6 on 2020-07-15 04:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('blog', '0002_goal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('hidden_note', models.BooleanField(default=True)),
                ('wallpaper', models.ImageField(blank=True, null=True, upload_to='wallpapers/')),
                ('theme', models.CharField(blank=True, default='light', max_length=6)),
            ],
        ),
    ]
