# Generated by Django 3.0.6 on 2020-07-15 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_setting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='hidden_note',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='setting',
            name='theme',
            field=models.BooleanField(default=False),
        ),
    ]
