# Generated by Django 3.0.6 on 2020-07-15 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200716_0133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='hidden_note',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='setting',
            name='theme',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
